FROM ubuntu:18.04
MAINTAINER you@youremail.com

RUN apt-get update && apt-get install -y vim curl wget git jq python nano unzip uuid-runtime iputils-ping dnsutils ca-certificates netcat telnet ruby sshpass

RUN ruby -v