---
platform: linux

params:
  DEBUG:
  OUTPUT_FILE_NAME:
  PARAM_NAME:
  OPSMAN_HOST:
  OPSMAN_SSHPASS:

inputs:
  - name: platform-automation-tasks

outputs:
  - name: output-folder

run:
  path: platform-automation-tasks/sandbox/tasks/update-ldap-cert/task.sh
